import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from 'next/link';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={geistSans.variable}>
        <nav className="flex items-center justify-between p-6 bg-gray-800 text-white">
          <Link href="/" className="text-xl font-bold">
            Crowdfunding Platform
          </Link>
          <div className="flex space-x-4">
            <Link href="/home" className="hover:text-gray-300">
              Home
            </Link>
            <Link href="/about" className="hover:text-gray-300">
              About
            </Link>
            <Link href="/contact" className="hover:text-gray-300">
              Contact
            </Link>
            <Link href="/campaign/create" className="hover:text-gray-300">
              Create Campaign
            </Link>
            <Link href="/campaigns" className="hover:text-gray-300">
              View Campaigns
            </Link>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
